var guiData = {
	"version": 2,
	"magic": "cantk",
	"meta": {
		"general": {
			"appid": "f20107cdef7843f7ba617bbc81d89989",
			"appversion": "1.0.0",
			"appname": "PhaserDemo",
			"appdesc": "PhaserDemo",
			"gapversion": "1.0",
			"allowImported": false,
			"screenscale": "fix-width",
			"orientation": "portrait",
			"developer": "Unkown <unkown@tangide.com>",
			"appIcon": "/drawapp8/images/appicons/96.png",
			"screenShot1": "",
			"screenShot2": "",
			"screenShot3": ""
		},
		"extlibs": [],
		"docChangedTime": 1460777275206,
		"docSavedTime": 1460777278121,
		"features": {},
		"assetsGroupConfig": {
			"version": "1.0",
			"groups": {
				"dialog": [
					"assets/dialog_bg.png",
					"assets/images.json",
					"assets/images.png"
				],
				"scene": [
					"assets/controls/button_active.png",
					"assets/controls/button_normal.png",
					"assets/controls/digits_label.png"
				],
				"__base__": [
					"index.html",
					"myapp.js",
					"deps.js",
					"cantk/css/cantk.css",
					"cantk/js/cantk-core.js",
					"cantk/js/webapp_init.js"
				]
			},
			"scenes": {
				"dialog": [
					"dialog"
				],
				"scene": [
					"scene"
				]
			}
		}
	},
	"deviceConfig": {
		"name": "general",
		"platform": "android",
		"lcdDensity": "hdpi"
	},
	"docid": "cn_releasec00948c0-035b-11e6-b377-cd913ea95c7a",
	"wm": {
		"type": "ui-window-manager",
		"name": "window-manager",
		"uid": 16616,
		"z": 0,
		"w": 480,
		"h": 854,
		"pivotX": 0.5,
		"pivotY": 0.5,
		"rotation": 0,
		"opacity": 1,
		"hMargin": 0,
		"vMargin": 0,
		"scaleX": 1,
		"scaleY": 1,
		"runtimeVisible": true,
		"enable": true,
		"visible": true,
		"text": "",
		"x": 0,
		"y": 0,
		"style": {
			"lineWidth": 2,
			"lineColor": "Green",
			"fillColor": "Black",
			"textColor": "Black",
			"fontSize": 24,
			"fontFamily": "serif"
		},
		"current": 1,
		"sceneIdIndex": 0,
		"xAttr": 0,
		"yAttr": 0,
		"widthAttr": 2,
		"heightAttr": 0,
		"xParam": 1,
		"yParam": 1,
		"widthParam": 1,
		"heightParam": 1,
		"images": {
			"display": 2,
			"force-landscape-tips": "cantk-game/assets/images/force_landscape.png",
			"force-portrait-tips": "cantk-game/assets/images/force_portrait.png"
		},
		"events": {
			"onClick": null,
			"onChanged": null
		},
		"settings": {},
		"children": [
			{
				"type": "ui-dialog",
				"name": "dialog",
				"uid": 11662,
				"z": 0,
				"w": 480,
				"h": 854,
				"pivotX": 0.5,
				"pivotY": 0.5,
				"rotation": 0,
				"opacity": 1,
				"hMargin": 0,
				"vMargin": 0,
				"scaleX": 1,
				"scaleY": 1,
				"runtimeVisible": true,
				"enable": true,
				"visible": true,
				"text": "",
				"locked": false,
				"x": 0,
				"y": 0,
				"style": {
					"lineWidth": 2,
					"lineColor": "Green",
					"fillColor": "",
					"textColor": "Black",
					"fontSize": 16,
					"fontFamily": "serif"
				},
				"animHint": "none",
				"sceneId": "1460760358403_069792",
				"xAttr": 3,
				"yAttr": 3,
				"widthAttr": 2,
				"heightAttr": 2,
				"xParam": 1,
				"yParam": 1,
				"widthParam": 1,
				"heightParam": 1,
				"images": {
					"display": 2
				},
				"events": {
					"onClick": null,
					"onSystemInit": null,
					"onLoad": null,
					"onOpen": null,
					"onBeforeOpen": null,
					"onClose": null,
					"onSwitchToBack": null,
					"onSwitchToFront": null,
					"onGesture": null,
					"onKeyDown": null,
					"onKeyUp": null,
					"onRelayout": null,
					"onUnload": null
				},
				"settings": {},
				"children": [
					{
						"type": "ui-image",
						"name": "image",
						"uid": 14168,
						"z": 0,
						"w": 461,
						"h": 696,
						"pivotX": 0.5,
						"pivotY": 0.5,
						"rotation": 0,
						"opacity": 1,
						"hMargin": 0,
						"vMargin": 0,
						"scaleX": 1,
						"scaleY": 1,
						"runtimeVisible": true,
						"enable": true,
						"visible": true,
						"text": "",
						"x": 9,
						"y": 79,
						"style": {
							"lineWidth": 2,
							"lineColor": "#7d471b",
							"fillColor": "White",
							"textColor": "Blue",
							"fontSize": 16,
							"fontFamily": "sans"
						},
						"keepSizeWithImage": false,
						"xAttr": 3,
						"yAttr": 3,
						"widthAttr": 0,
						"heightAttr": 0,
						"xParam": 1,
						"yParam": 1,
						"widthParam": 1,
						"heightParam": 1,
						"imageScaleX": 1,
						"imageScaleY": 1,
						"images": {
							"display": 3,
							"default_bg": "assets/dialog_bg.png"
						},
						"events": {
							"onClick": null,
							"onUpdateTransform": null,
							"onDoubleClick": null
						},
						"children": [
							{
								"type": "ui-button",
								"name": "button",
								"uid": 11205,
								"z": 0,
								"w": 88,
								"h": 88,
								"pivotX": 0.5,
								"pivotY": 0.5,
								"rotation": 0,
								"opacity": 1,
								"hMargin": 5,
								"vMargin": 5,
								"scaleX": 1,
								"scaleY": 1,
								"runtimeVisible": true,
								"enable": true,
								"visible": true,
								"text": "",
								"x": 186,
								"y": 601,
								"style": {
									"lineWidth": 2,
									"lineColor": "Red",
									"fillColor": "White",
									"textColor": "#b8b8b8",
									"fontSize": 18,
									"fontFamily": "serif"
								},
								"xAttr": 3,
								"yAttr": 2,
								"widthAttr": 0,
								"heightAttr": 0,
								"xParam": 1,
								"yParam": 0.8635057471264368,
								"widthParam": 1,
								"heightParam": 1,
								"imageScaleX": 1,
								"imageScaleY": 1,
								"images": {
									"display": 3,
									"active_bg": "assets/images.json#game_tc_btnbacka.png",
									"real-image-holaverse/storage/read.php?path=68069088-4b48-4fce-a8f6-b735148e7173/f20107cdef7843f7ba617bbc81d89989/images.json": "assets/images.png",
									"normal_bg": "assets/images.json#game_tc_btnbackb.png",
									"disable_bg": "assets/images.json#game_tc_btnbacka.png"
								},
								"events": {
									"onClick": "this.closeWindow();",
									"onUpdateTransform": null
								},
								"children": []
							},
							{
								"type": "ui-grid-view-x",
								"name": "grid-view-x",
								"uid": 14168,
								"z": 1,
								"w": 330,
								"h": 453,
								"pivotX": 0.5,
								"pivotY": 0.5,
								"rotation": 0,
								"opacity": 1,
								"hMargin": 0,
								"vMargin": 0,
								"scaleX": 1,
								"scaleY": 1,
								"spacer": 0,
								"runtimeVisible": true,
								"enable": true,
								"visible": true,
								"text": "",
								"x": 65,
								"y": 130,
								"style": {
									"lineWidth": 2,
									"lineColor": "White",
									"fillColor": "White",
									"textColor": "Blue",
									"fontSize": 16,
									"fontFamily": "sans"
								},
								"virtualWidth": 330,
								"virtualHeight": 755,
								"showOutside": true,
								"scrollAnimationDuration": 800,
								"cols": 2,
								"rows": 3,
								"isVertical": true,
								"xAttr": 3,
								"yAttr": 0,
								"widthAttr": 0,
								"heightAttr": 0,
								"xParam": 1,
								"yParam": 1,
								"widthParam": 1,
								"heightParam": 1,
								"imageScaleX": 0.407,
								"imageScaleY": 0.388,
								"images": {
									"display": 3
								},
								"events": {
									"onClick": null,
									"onScrolling": null,
									"onScrollDone": null
								},
								"children": [
									{
										"type": "ui-group",
										"name": "group",
										"uid": 17605,
										"z": 0,
										"w": 165,
										"h": 151,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"roundRadius": 12,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "",
										"x": 0,
										"y": 0,
										"style": {
											"lineWidth": 2,
											"lineColor": "",
											"fillColor": "",
											"textColor": "Blue",
											"fontSize": 24
										},
										"xAttr": 0,
										"yAttr": 0,
										"widthAttr": 0,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": null,
											"onInit": null
										},
										"children": [
											{
												"type": "ui-image",
												"name": "image",
												"uid": 14168,
												"z": 0,
												"w": 92,
												"h": 87,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 0,
												"vMargin": 0,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "",
												"x": 36,
												"y": 32,
												"style": {
													"lineWidth": 2,
													"lineColor": "#7d471b",
													"fillColor": "White",
													"textColor": "Blue",
													"fontSize": 16,
													"fontFamily": "sans"
												},
												"keepSizeWithImage": false,
												"xAttr": 3,
												"yAttr": 3,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"imageScaleX": 1,
												"imageScaleY": 1,
												"images": {
													"display": 3,
													"default_bg": "assets/images.json#game_tc_star.png",
													"real-image-holaverse/storage/read.php?path=68069088-4b48-4fce-a8f6-b735148e7173/f20107cdef7843f7ba617bbc81d89989/images.json": "assets/images.png"
												},
												"events": {
													"onClick": null,
													"onUpdateTransform": null,
													"onDoubleClick": null
												},
												"children": []
											}
										]
									},
									{
										"type": "ui-group",
										"name": "group-1",
										"uid": 17605,
										"z": 10,
										"w": 165,
										"h": 151,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"roundRadius": 12,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "",
										"x": 165,
										"y": 0,
										"style": {
											"lineWidth": 2,
											"lineColor": "",
											"fillColor": "",
											"textColor": "Blue",
											"fontSize": 24
										},
										"xAttr": 0,
										"yAttr": 0,
										"widthAttr": 0,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": null,
											"onInit": null
										},
										"children": [
											{
												"type": "ui-image",
												"name": "image",
												"uid": 14168,
												"z": 0,
												"w": 92,
												"h": 87,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 0,
												"vMargin": 0,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "",
												"x": 36,
												"y": 32,
												"style": {
													"lineWidth": 2,
													"lineColor": "#7d471b",
													"fillColor": "White",
													"textColor": "Blue",
													"fontSize": 16,
													"fontFamily": "sans"
												},
												"keepSizeWithImage": false,
												"xAttr": 3,
												"yAttr": 3,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"imageScaleX": 1,
												"imageScaleY": 1,
												"images": {
													"display": 3,
													"default_bg": "assets/images.json#game_tc_star.png",
													"real-image-holaverse/storage/read.php?path=68069088-4b48-4fce-a8f6-b735148e7173/f20107cdef7843f7ba617bbc81d89989/images.json": "assets/images.png"
												},
												"events": {
													"onClick": null,
													"onUpdateTransform": null,
													"onDoubleClick": null
												},
												"children": []
											}
										]
									},
									{
										"type": "ui-group",
										"name": "group-2",
										"uid": 17605,
										"z": 20,
										"w": 165,
										"h": 151,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"roundRadius": 12,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "",
										"x": 0,
										"y": 151,
										"style": {
											"lineWidth": 2,
											"lineColor": "",
											"fillColor": "",
											"textColor": "Blue",
											"fontSize": 24
										},
										"xAttr": 0,
										"yAttr": 0,
										"widthAttr": 0,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": null,
											"onInit": null
										},
										"children": [
											{
												"type": "ui-image",
												"name": "image",
												"uid": 14168,
												"z": 0,
												"w": 92,
												"h": 87,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 0,
												"vMargin": 0,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "",
												"x": 36,
												"y": 32,
												"style": {
													"lineWidth": 2,
													"lineColor": "#7d471b",
													"fillColor": "White",
													"textColor": "Blue",
													"fontSize": 16,
													"fontFamily": "sans"
												},
												"keepSizeWithImage": false,
												"xAttr": 3,
												"yAttr": 3,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"imageScaleX": 1,
												"imageScaleY": 1,
												"images": {
													"display": 3,
													"default_bg": "assets/images.json#game_tc_star.png",
													"real-image-holaverse/storage/read.php?path=68069088-4b48-4fce-a8f6-b735148e7173/f20107cdef7843f7ba617bbc81d89989/images.json": "assets/images.png"
												},
												"events": {
													"onClick": null,
													"onUpdateTransform": null,
													"onDoubleClick": null
												},
												"children": []
											}
										]
									},
									{
										"type": "ui-group",
										"name": "group-3",
										"uid": 17605,
										"z": 30,
										"w": 165,
										"h": 151,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"roundRadius": 12,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "",
										"x": 165,
										"y": 151,
										"style": {
											"lineWidth": 2,
											"lineColor": "",
											"fillColor": "",
											"textColor": "Blue",
											"fontSize": 24
										},
										"xAttr": 0,
										"yAttr": 0,
										"widthAttr": 0,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": null,
											"onInit": null
										},
										"children": [
											{
												"type": "ui-image",
												"name": "image",
												"uid": 14168,
												"z": 0,
												"w": 92,
												"h": 87,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 0,
												"vMargin": 0,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "",
												"x": 36,
												"y": 32,
												"style": {
													"lineWidth": 2,
													"lineColor": "#7d471b",
													"fillColor": "White",
													"textColor": "Blue",
													"fontSize": 16,
													"fontFamily": "sans"
												},
												"keepSizeWithImage": false,
												"xAttr": 3,
												"yAttr": 3,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"imageScaleX": 1,
												"imageScaleY": 1,
												"images": {
													"display": 3,
													"default_bg": "assets/images.json#game_tc_star.png",
													"real-image-holaverse/storage/read.php?path=68069088-4b48-4fce-a8f6-b735148e7173/f20107cdef7843f7ba617bbc81d89989/images.json": "assets/images.png"
												},
												"events": {
													"onClick": null,
													"onUpdateTransform": null,
													"onDoubleClick": null
												},
												"children": []
											}
										]
									},
									{
										"type": "ui-group",
										"name": "group-4",
										"uid": 17605,
										"z": 40,
										"w": 165,
										"h": 151,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"roundRadius": 12,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "",
										"x": 0,
										"y": 302,
										"style": {
											"lineWidth": 2,
											"lineColor": "",
											"fillColor": "",
											"textColor": "Blue",
											"fontSize": 24
										},
										"xAttr": 0,
										"yAttr": 0,
										"widthAttr": 0,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": null,
											"onInit": null
										},
										"children": [
											{
												"type": "ui-image",
												"name": "image",
												"uid": 14168,
												"z": 0,
												"w": 92,
												"h": 87,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 0,
												"vMargin": 0,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "",
												"x": 36,
												"y": 32,
												"style": {
													"lineWidth": 2,
													"lineColor": "#7d471b",
													"fillColor": "White",
													"textColor": "Blue",
													"fontSize": 16,
													"fontFamily": "sans"
												},
												"keepSizeWithImage": false,
												"xAttr": 3,
												"yAttr": 3,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"imageScaleX": 1,
												"imageScaleY": 1,
												"images": {
													"display": 3,
													"default_bg": "assets/images.json#game_tc_star.png",
													"real-image-holaverse/storage/read.php?path=68069088-4b48-4fce-a8f6-b735148e7173/f20107cdef7843f7ba617bbc81d89989/images.json": "assets/images.png"
												},
												"events": {
													"onClick": null,
													"onUpdateTransform": null,
													"onDoubleClick": null
												},
												"children": []
											}
										]
									},
									{
										"type": "ui-group",
										"name": "group-5",
										"uid": 17605,
										"z": 50,
										"w": 165,
										"h": 151,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"roundRadius": 12,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "",
										"x": 165,
										"y": 302,
										"style": {
											"lineWidth": 2,
											"lineColor": "",
											"fillColor": "",
											"textColor": "Blue",
											"fontSize": 24
										},
										"xAttr": 0,
										"yAttr": 0,
										"widthAttr": 0,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": null,
											"onInit": null
										},
										"children": [
											{
												"type": "ui-image",
												"name": "image",
												"uid": 14168,
												"z": 0,
												"w": 92,
												"h": 87,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 0,
												"vMargin": 0,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "",
												"x": 36,
												"y": 32,
												"style": {
													"lineWidth": 2,
													"lineColor": "#7d471b",
													"fillColor": "White",
													"textColor": "Blue",
													"fontSize": 16,
													"fontFamily": "sans"
												},
												"keepSizeWithImage": false,
												"xAttr": 3,
												"yAttr": 3,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"imageScaleX": 1,
												"imageScaleY": 1,
												"images": {
													"display": 3,
													"default_bg": "assets/images.json#game_tc_star.png",
													"real-image-holaverse/storage/read.php?path=68069088-4b48-4fce-a8f6-b735148e7173/f20107cdef7843f7ba617bbc81d89989/images.json": "assets/images.png"
												},
												"events": {
													"onClick": null,
													"onUpdateTransform": null,
													"onDoubleClick": null
												},
												"children": []
											}
										]
									},
									{
										"type": "ui-group",
										"name": "group-6",
										"uid": 17605,
										"z": 60,
										"w": 165,
										"h": 151,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"roundRadius": 12,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "",
										"x": 0,
										"y": 453,
										"style": {
											"lineWidth": 2,
											"lineColor": "",
											"fillColor": "",
											"textColor": "Blue",
											"fontSize": 24
										},
										"xAttr": 0,
										"yAttr": 0,
										"widthAttr": 0,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": null,
											"onInit": null
										},
										"children": [
											{
												"type": "ui-image",
												"name": "image",
												"uid": 14168,
												"z": 0,
												"w": 92,
												"h": 87,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 0,
												"vMargin": 0,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "",
												"x": 36,
												"y": 32,
												"style": {
													"lineWidth": 2,
													"lineColor": "#7d471b",
													"fillColor": "White",
													"textColor": "Blue",
													"fontSize": 16,
													"fontFamily": "sans"
												},
												"keepSizeWithImage": false,
												"xAttr": 3,
												"yAttr": 3,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"imageScaleX": 1,
												"imageScaleY": 1,
												"images": {
													"display": 3,
													"default_bg": "assets/images.json#game_tc_star.png",
													"real-image-holaverse/storage/read.php?path=68069088-4b48-4fce-a8f6-b735148e7173/f20107cdef7843f7ba617bbc81d89989/images.json": "assets/images.png"
												},
												"events": {
													"onClick": null,
													"onUpdateTransform": null,
													"onDoubleClick": null
												},
												"children": []
											}
										]
									},
									{
										"type": "ui-group",
										"name": "group-7",
										"uid": 17605,
										"z": 70,
										"w": 165,
										"h": 151,
										"pivotX": 0.5,
										"pivotY": 0.5,
										"rotation": 0,
										"opacity": 1,
										"hMargin": 0,
										"vMargin": 0,
										"scaleX": 1,
										"scaleY": 1,
										"roundRadius": 12,
										"runtimeVisible": true,
										"enable": true,
										"visible": true,
										"text": "",
										"x": 165,
										"y": 453,
										"style": {
											"lineWidth": 2,
											"lineColor": "",
											"fillColor": "",
											"textColor": "Blue",
											"fontSize": 24
										},
										"xAttr": 0,
										"yAttr": 0,
										"widthAttr": 0,
										"heightAttr": 0,
										"xParam": 1,
										"yParam": 1,
										"widthParam": 1,
										"heightParam": 1,
										"images": {
											"display": 2
										},
										"events": {
											"onClick": null,
											"onInit": null
										},
										"children": [
											{
												"type": "ui-image",
												"name": "image",
												"uid": 14168,
												"z": 0,
												"w": 92,
												"h": 87,
												"pivotX": 0.5,
												"pivotY": 0.5,
												"rotation": 0,
												"opacity": 1,
												"hMargin": 0,
												"vMargin": 0,
												"scaleX": 1,
												"scaleY": 1,
												"runtimeVisible": true,
												"enable": true,
												"visible": true,
												"text": "",
												"x": 36,
												"y": 32,
												"style": {
													"lineWidth": 2,
													"lineColor": "#7d471b",
													"fillColor": "White",
													"textColor": "Blue",
													"fontSize": 16,
													"fontFamily": "sans"
												},
												"keepSizeWithImage": false,
												"xAttr": 3,
												"yAttr": 3,
												"widthAttr": 0,
												"heightAttr": 0,
												"xParam": 1,
												"yParam": 1,
												"widthParam": 1,
												"heightParam": 1,
												"imageScaleX": 1,
												"imageScaleY": 1,
												"images": {
													"display": 3,
													"default_bg": "assets/images.json#game_tc_star.png",
													"real-image-holaverse/storage/read.php?path=68069088-4b48-4fce-a8f6-b735148e7173/f20107cdef7843f7ba617bbc81d89989/images.json": "assets/images.png"
												},
												"events": {
													"onClick": null,
													"onUpdateTransform": null,
													"onDoubleClick": null
												},
												"children": []
											}
										]
									}
								]
							}
						]
					}
				]
			},
			{
				"type": "ui-scene",
				"name": "scene",
				"uid": 16617,
				"z": 1,
				"w": 480,
				"h": 854,
				"pivotX": 0.5,
				"pivotY": 0.5,
				"rotation": 0,
				"opacity": 1,
				"hMargin": 0,
				"vMargin": 0,
				"scaleX": 1,
				"scaleY": 1,
				"runtimeVisible": true,
				"enable": true,
				"visible": true,
				"text": "",
				"locked": false,
				"x": 0,
				"y": 0,
				"style": {
					"lineWidth": 2,
					"lineColor": "#C8C8C8",
					"fillColor": "#2F3234",
					"textColor": "Blue",
					"fontSize": 15,
					"fontFamily": "sans"
				},
				"gravityY": 10,
				"pixelsPerMeter": 100,
				"virtualWidth": 0,
				"virtualHeight": 0,
				"xOffset": 0,
				"yOffset": 0,
				"animHint": "none",
				"sceneId": "1460761287527_244962",
				"xAttr": 0,
				"yAttr": 0,
				"widthAttr": 2,
				"heightAttr": 2,
				"xParam": 1,
				"yParam": 1,
				"widthParam": 1,
				"heightParam": 1,
				"images": {
					"display": 3
				},
				"events": {
					"onClick": null,
					"onSystemInit": null,
					"onLoad": null,
					"onOpen": null,
					"onBeforeOpen": null,
					"onClose": null,
					"onSwitchToBack": null,
					"onSwitchToFront": null,
					"onGesture": null,
					"onKeyDown": null,
					"onKeyUp": null,
					"onPointerDown": null,
					"onPointerMove": null,
					"onPointerUp": null,
					"onDoubleClick": null,
					"onMultiTouch": null,
					"onSwipeLeft": null,
					"onSwipeRight": null,
					"onSwipeUp": null,
					"onSwipeDown": null,
					"onRelayout": null,
					"onUnload": null
				},
				"settings": {},
				"children": [
					{
						"type": "ui-button",
						"name": "button-2",
						"uid": 11205,
						"z": 2,
						"w": 200,
						"h": 69,
						"pivotX": 0.5,
						"pivotY": 0.5,
						"rotation": 0,
						"opacity": 1,
						"hMargin": 5,
						"vMargin": 5,
						"scaleX": 1,
						"scaleY": 1,
						"runtimeVisible": true,
						"enable": true,
						"visible": true,
						"text": "Close",
						"x": 138,
						"y": 476,
						"style": {
							"lineWidth": 2,
							"lineColor": "Red",
							"fillColor": "White",
							"textColor": "#b8b8b8",
							"fontSize": 18,
							"fontFamily": "serif"
						},
						"xAttr": 0,
						"yAttr": 0,
						"widthAttr": 0,
						"heightAttr": 0,
						"xParam": 1,
						"yParam": 1,
						"widthParam": 1,
						"heightParam": 1,
						"imageScaleX": 1,
						"imageScaleY": 1,
						"images": {
							"display": 3,
							"active_bg": "assets/controls/button_active.png",
							"normal_bg": "assets/controls/button_normal.png",
							"disable_bg": "assets/controls/button_active.png"
						},
						"events": {
							"onClick": "this.closeWindow();",
							"onUpdateTransform": null
						},
						"children": []
					},
					{
						"type": "ui-bitmap-font-text",
						"name": "bitmap-font-text",
						"uid": 10345,
						"z": 3,
						"w": 320,
						"h": 80,
						"pivotX": 0.5,
						"pivotY": 0.5,
						"rotation": 0,
						"opacity": 1,
						"hMargin": 3,
						"vMargin": 3,
						"scaleX": 1,
						"scaleY": 1,
						"spacer": 0,
						"runtimeVisible": true,
						"enable": true,
						"visible": true,
						"text": "1024",
						"x": 80,
						"y": 202,
						"style": {
							"lineWidth": 1,
							"lineColor": "Orange",
							"fillColor": "White",
							"textColor": "Blue",
							"fontSize": 48,
							"fontFamily": "sans",
							"imageBorder": 10,
							"textAlignH": "left",
							"startColor": "Green",
							"endColor": "Green",
							"shadowColor": "Black",
							"shadowBlur": 5,
							"shadowOffsetX": 2,
							"shadowOffsetY": 2
						},
						"allText": "1234567890ms-.:",
						"textAlignment": "center",
						"imageRows": 3,
						"imageColumns": 5,
						"xAttr": 3,
						"yAttr": 0,
						"widthAttr": 0,
						"heightAttr": 0,
						"xParam": 1,
						"yParam": 1,
						"widthParam": 1,
						"heightParam": 1,
						"images": {
							"display": 4,
							"normal_fg": "assets/controls/digits_label.png"
						},
						"events": {
							"onClick": null,
							"onUpdateTransform": null
						},
						"children": []
					}
				]
			}
		]
	},
	"fileList": []
}
